version: "3"

services:
    mysql:
        image: mysql:8.1
        volumes:
            - ./database_data:/var/lib/mysql
        ports:
            - "3306:3306"
        expose:
            - "3306"
        environment:
            MYSQL_DATABASE: app
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
        networks:
            - link-network
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
        networks:
            - link-network
    php:
        build:
            dockerfile: Dockerfile
            context: ./docker/php/
        volumes:
            - ./:/var/www
        working_dir: /var/www
        networks:
            - link-network
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            - PHP_IDE_CONFIG=serverName=localhost
            - XDEBUG_SESSION=PHPSTORM
#
networks:
    link-network:
        driver: bridge
